{
    "swagger": "2.0",
    "info": {
        "version": "v1.0",
        "title": "finfitapp API",
        "description": "## Welcome\n\nThis is a place to put general notes and extra information, for internal use.\n\nTo get started designing/documenting this API, select a version on the left."
    },
    "host": "api.finfitapp.com:8081",
    "basePath": "/api/v1",
    "schemes": [
        "http"
    ],
    "consumes": [
        "application/javascript"
    ],
    "produces": [
        "application/javascript"
    ],
    "securityDefinitions": {
        "oauth2": {
            "type": "oauth2",
            "flow": "implicit",
            "scopes": {},
            "authorizationUrl": ""
        }
    },
    "paths": {
        "/activities/{activityId}": {
            "parameters": [
                {
                    "name": "activityId",
                    "in": "path",
                    "required": true,
                    "type": "string"
                }
            ],
            "post": {
                "operationId": "POST_activities-activityId",
                "summary": "Save user action on Activity",
                "description": "<p><h4>Сохранение выбора  реакции пользователя на активность</h4>\n<br>\nДанное API сохраняет результат действий пользователя с Активностей - выбор одного из двух вариантов ответа.</p>\n<br>\n<br>\n<p>В вызове передается ИД активности (activityId) и содержание атрибута <code>buttonResponse </code> кнопки, которая была нажата.\n<br>\n<br>\n<code>buttonResponse </code> содержится в объекте Activity, предедыдущего  вызова (<code><a href=\"/v1.0/activities-widget/get-activity-details\" class=\"undefined\">Get all new activities and their details</a></code> для получения деталей всех новых актвиностей.</p>\n",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "buttonResponse": {
                                    "type": "string"
                                }
                            },
                            "example": {
                                "buttonResponse": "take"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/recomnedations": {
            "get": {
                "operationId": "GET_recomnedations",
                "summary": "Get recommnedation details",
                "description": "<p><H3>Получение  рекоммендаций клиента</h3></p>\n<p>API предоставляет детали всех рекомендаций, доступных клиенту (объект <code>recomendation </code>). Данные предоставляются как массив данного объекта.\n<br></p>\n<p>Модель объекта рекомендации: <a href=\"/v1.0/models/recommnedation\" class=\"undefined\">Recommnedation</a></p>\n<br>\n<b>Статусы рекомендаций</b>\n<p>API предоставляет рекомендандации в следующих статусах:</p>\n<ul>\n<li><code>New</code> (новые рекоммендации)</li>\n<li><code>Active</code> (Активные рекомендации, которые клиент принял)</li>\n<li><code>Filled</code> (Выполненые рекоммендации)</li>\n<li><code>Expired</code> (просроченные, неактивные рекоммендации)</li>\n</ul>\n<p>Для получения рекоммендаций в определенном статусе, необходимо использовать query string - фильтр <code>recommendationStatus</code>. Пример URL для получения всех выполненых рекоммендаций:\n<br></p>\n<p><i> <code> /recommendations?recommendationStatus=filled  </code></i></p>\n<br>\n<b>Сортировка данных</b><br>\nРекоммендации в масиве отсортированы на основе атрибута recommendationId, по возрастанию.\n<br>\n<p><h4>Первое окно Рекомендауии  </h4>\n<img src=\"https://snag.gy/HyeMf3.jpg\"></p>\n<br>\n<p><h4>Второе окно детализации Рекомендации  </h4>\n<img src=\"https://snag.gy/Pa6D3U.jpg\"></p>\n",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "recommendationStatus",
                        "in": "query",
                        "description": "статус рекоммендации, которые будут содержатся в ответе",
                        "required": false,
                        "type": "string",
                        "enum": [
                            "new",
                            "active",
                            "filled",
                            "expired"
                        ]
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": "{\"type\":\"object\",\"properties\":{\"recommendationId\":{\"type\":\"integer\"},\"recommendationStatus\":{\"type\":\"string\",\"description\":\"статус рекоммендации.\",\"enum\":[\"new\",\"active\",\"filled\",\"expired\"]},\"recommendationType\":{\"type\":\"string\",\"description\":\"тип рекомендации.  Испроьзуется для текста шапки карточки с рекомендацие\"},\"recommendationCategory\":{\"type\":\"string\",\"description\":\"тип рекомендации.  Испроьзуется для текста шапки карточки с рекомендацие\"},\"occurence\":{\"type\":\"string\",\"description\":\"Время следующего появления рекомендаций. возможные вараианты: \\\"next Monday\\\"; \\\"next Week\\\"; \\\"next Month\\\"\"},\"recommendationAmount\":{\"type\":\"number\",\"description\":\"сума на которую расчитывает реукомендация\"},\"currency_id\":{\"type\":\"string\",\"description\":\"3х значный ISO код валюты\"},\"usedCard\":{\"type\":\"string\",\"description\":\"номер - id используемой карты\"},\"cardAssociation\":{\"type\":\"string\",\"description\":\"Реестр карточных ассоциаций\",\"enum\":[\"VISA\",\"MC\",\"AE\"]},\"1stStepCardDetails\":{\"type\":\"object\",\"description\":\"детали для первого окна\",\"required\":[\"buttonText\"],\"properties\":{\"buttonText\":{\"type\":\"string\",\"description\":\"текст на кнопке перехода на 2е окно\"},\"rows\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"row\":{\"type\":\"string\",\"description\":\"id строки детализации текста\"},\"textLeft\":{\"type\":\"string\"},\"textRight\":{\"type\":\"string\"},\"textColour\":{\"type\":\"string\"}}}}}},\"2ndStepCardDetails\":{\"type\":\"object\",\"description\":\"детали для первого окна\",\"required\":[\"cardDetailText\",\"cardDetailHeading\",\"cardDetailButtons\"],\"properties\":{\"cardDetailText\":{\"type\":\"string\",\"description\":\"текст для второго окна\"},\"cardDetailHeading\":{\"type\":\"string\",\"description\":\"текст - заговолог для второго окна\"},\"cardDetailButtons\":{\"type\":\"array\",\"description\":\"поле с деталями кнопок\",\"items\":{\"type\":\"object\",\"properties\":{\"ButtonText\":{\"type\":\"string\",\"description\":\"текст на кнопке\"},\"possitiveFlag\":{\"type\":\"boolean\",\"description\":\"флаг определяющий если кнопка для позитивного ответа (\\\"1\\\" = positive)\"},\"buttonResponse\":{\"type\":\"string\"}},\"required\":[\"ButtonText\",\"possitiveFlag\",\"buttonResponse\"]}}}}},\"required\":[\"recommendationId\",\"recommendationStatus\",\"recommendationType\",\"recommendationCategory\",\"occurence\",\"recommendationAmount\",\"currency_id\",\"usedCard\",\"cardAssociation\",\"1stStepCardDetails\",\"2ndStepCardDetails\"],",
                        "examples": {
                            "application/json": {
                                "recommendationId": 16983,
                                "recommendationStatus": "new",
                                "recommendationType": "Auchan",
                                "recommendationCategory": "Groceries",
                                "occurence": "every Tuesday",
                                "recommendationAmount": 260,
                                "currency_id": "EUR",
                                "usedCard": "0039",
                                "cardAssociation": "MC",
                                "1stStepCardDetails": {
                                    "buttonText": "Take recommendation",
                                    "rows": [
                                        {
                                            "row": "",
                                            "textLeft": "",
                                            "textRight": "",
                                            "textColour": ""
                                        }
                                    ]
                                },
                                "2ndStepCardDetails": {
                                    "cardDetailText": "This recomendation is based on most of your Groceries shopping done around Tuesday every other week. \n Milk \n Yogurt \n Grapefruit \n Banana",
                                    "cardDetailHeading": "We have calculated your typical shopping list and have thrown in a special from our partner, Auchan",
                                    "cardDetailButtons": [
                                        {
                                            "ButtonText": "Leave it",
                                            "possitiveFlag": false,
                                            "buttonResponse": "leave"
                                        },
                                        {
                                            "ButtonText": "Take it",
                                            "possitiveFlag": true,
                                            "buttonResponse": "take"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        },
        "/dashboard": {
            "get": {
                "operationId": "GET_dashboard",
                "summary": "Data for main dashboard",
                "description": "<p>Предоставляет данные для отображения основных карточек, а то:</p>\n<ul>\n<li>\n<p>Activity</p>\n<ul>\n<li>текст для отображения на карточке Activity</li>\n<li>количество новых Активностей</li>\n</ul>\n</li>\n<li>\n<p>Reccomendation</p>\n<ul>\n<li>текст для отображения на карточке Recommendation</li>\n<li>количество новых рекомендаций</li>\n</ul>\n</li>\n<li>\n<p>Stats</p>\n<ul>\n<li>текст для отображения на карточке Stats</li>\n</ul>\n</li>\n</ul>\n<br>\n<img src=\"https://snag.gy/lXAmCY.jpg\">",
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "activityCardText": {
                                    "type": "string",
                                    "description": "Текст карточки Activity главного экрана"
                                },
                                "recommendationCardText": {
                                    "type": "string",
                                    "description": "Текст карточки Recommendation главного экрана"
                                },
                                "statsCardText": {
                                    "type": "string",
                                    "description": "Текст карточки Stats главного экрана"
                                }
                            },
                            "required": [
                                "activityCardText",
                                "recommendationCardText",
                                "statsCardText"
                            ]
                        },
                        "examples": {
                            "application/javascript": {
                                "activityCardText": "5 questions to answer to better categorize your spending and help stay on track, including your payment in Starbucks",
                                "recommendationCardText": "1 recommendation tracking for you so far. We will follow up when we have more.",
                                "statsCardText": "5 out of 7 recommendations followed, including your Trip Plan. 260 points up, good for you! Overall spending for the past 7 days – 1 865 EUR"
                            }
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "operationId": "GET_stats",
                "summary": "Client Statistics",
                "description": "<p><H3>Получение статистики клиента</h3></p>\n<p>API предоставляет статистику клиента, по  по всем 3 карточкам, на экране статисики:</p>\n<ol>\n<li>FinFit  пирамида </br></li>\n<li>Список категорий </br></li>\n</ol>\n<p><b>Период статистики </b>\n<br>По умолчанию статистика предоставляется за период <code>month</code> - календарный месяц. параметр передается как &quot;query string&quot; <code>period</code>.\n<br>Доступные периоды:</p>\n<ul>\n<li><code>day</code></li>\n<li><code>week</code></li>\n<li><code>2weeks</code></li>\n<li><code>month</code></li>\n<li><code>all</code></li>\n</ul>",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "period",
                        "in": "query",
                        "description": "Период, за который предоставляется статистика",
                        "required": false,
                        "type": "string",
                        "default": "month",
                        "enum": [
                            "day",
                            "week",
                            "2weeks",
                            "month",
                            "all"
                        ]
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": "{\"type\":\"object\",\"properties\":{\"ffPyramidCategories\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"pyramidCategoryVisibleName\":{\"type\":\"string\"},\"pyramidCategory\":{\"type\":\"string\"},\"TotalSum\":{\"type\":\"integer\"},\"Currency\":{\"type\":\"string\",\"description\":\"3х значный ISO код валюты трансакции\"},\"ffPoints\":{\"type\":\"integer\"}},",
                        "examples": {
                            "application/json": {
                                "ranking": {
                                    "ranking": "you can definitely improve your bang for a buck. Presently trailing <b> 30% </b> of your peer group"
                                },
                                "ffPyramidCategories": [
                                    {
                                        "pyramidCategoryVisibleName": "Higher Goals",
                                        "pyramidCategory": "higherGoals",
                                        "TotalSum": 7800,
                                        "Currency": "RUR",
                                        "ffPoints": 580
                                    },
                                    {
                                        "pyramidCategoryVisibleName": "Social desires",
                                        "pyramidCategory": "socialDesires",
                                        "TotalSum": 12580,
                                        "Currency": "RUR",
                                        "ffPoints": 2040
                                    },
                                    {
                                        "pyramidCategoryVisibleName": "Bare necessities",
                                        "pyramidCategory": "bareNecessities",
                                        "TotalSum": 880,
                                        "Currency": "RUR",
                                        "ffPoints": 30
                                    }
                                ],
                                "ffCategories": [
                                    {
                                        "ffCategoryVisibleName": "Groceries",
                                        "ffCategory": "groceries",
                                        "Operations": 22,
                                        "TotalSum": 13550,
                                        "Currency": "RUR",
                                        "ffPoints": 220
                                    },
                                    {
                                        "ffCategoryVisibleName": "FastFood",
                                        "ffCategory": "fastfood",
                                        "Operations": 38,
                                        "TotalSum": 8900,
                                        "Currency": "RUR",
                                        "ffPoints": 90
                                    },
                                    {
                                        "ffCategoryVisibleName": "Gas & Fuel",
                                        "ffCategory": "gasFuel",
                                        "Operations": 8,
                                        "TotalSum": 8800,
                                        "Currency": "RUR",
                                        "ffPoints": 105
                                    },
                                    {
                                        "ffCategoryVisibleName": "Restaurants",
                                        "ffCategory": "dining",
                                        "Operations": 19,
                                        "TotalSum": 7920,
                                        "Currency": "RUR",
                                        "ffPoints": 280
                                    },
                                    {
                                        "ffCategoryVisibleName": "Candy, Ice Cream",
                                        "ffCategory": "candyIceCream",
                                        "Operations": 14,
                                        "TotalSum": 7103,
                                        "Currency": "RUR",
                                        "ffPoints": 20
                                    },
                                    {
                                        "ffCategoryVisibleName": "Bakery",
                                        "ffCategory": "bakery",
                                        "Operations": 26,
                                        "TotalSum": 2940,
                                        "Currency": "RUR",
                                        "ffPoints": 50
                                    },
                                    {
                                        "ffCategoryVisibleName": "Clothing & Accessories",
                                        "ffCategory": "clothingAccessories",
                                        "Operations": 2,
                                        "TotalSum": 6640,
                                        "Currency": "RUR",
                                        "ffPoints": 310,
                                        "ffPointsRatio": 50
                                    },
                                    {
                                        "ffCategoryVisibleName": "Entertainment",
                                        "ffCategory": "entertainment",
                                        "Operations": 7,
                                        "TotalSum": 5816,
                                        "Currency": "RUR",
                                        "ffPoints": 560
                                    },
                                    {
                                        "ffCategoryVisibleName": "Pharmacy & Drugs",
                                        "ffCategory": "pharmacy",
                                        "Operations": 9,
                                        "TotalSum": 5443,
                                        "Currency": "RUR",
                                        "ffPoints": 150
                                    },
                                    {
                                        "ffCategoryVisibleName": "Alcohol",
                                        "ffCategory": "alcohol",
                                        "Operations": 3,
                                        "TotalSum": 4490,
                                        "Currency": "RUR",
                                        "ffPoints": 0
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        },
        "/activities": {
            "get": {
                "operationId": "GET_activities",
                "summary": "Get all new activities and their details",
                "description": "<p><H3>Получение деталей Активностей клиента</h3></p>\n<p>API предоставляет детали новых активностей, доступных клиенту (объект <code>activity </code>).\n<br></p>\n<p>Модель объекта активности: <a href=\"/v1.0/models/activity\" class=\"undefined\">Activity</a></p>\n<br>\n<p><b>Сортировка данных</b><br>\nАктивности в масиве отсортированы на основе атрибута activityId, по возрастанию.</p>\n<p><h4>Первое окно детализации Активности  </h4>\n<img src=\"https://snag.gy/pWbenq.jpg\"></p>\n<br>\n<h4>Второе окно детализации Активности  </h4>\n<br>\n<img src=\"https://snag.gy/WJ60ml.jpg\">",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": "{\"type\":\"object\",\"properties\":{\"activities\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"activityId\":{\"type\":\"integer\",\"description\":\"уникальный идентификатор активности в системе\"},\"datetime\":{\"type\":\"string\",\"description\":\"время и дата трансакции в UTC формате\"},\"trans_amt\":{\"type\":\"number\",\"description\":\"сума трансакции\"},\"trans_details\":{\"type\":\"string\",\"description\":\"Название места - merchant\"},\"trans_type\":{\"type\":\"string\",\"description\":\"Тип трансакции - online/offline. \"},\"currency_id\":{\"type\":\"string\",\"description\":\"3х значный ISO код валюты\"},\"categoryVisibleName\":{\"type\":\"string\",\"description\":\"название FF категории трансакции\"},\"usedCard\":{\"type\":\"string\",\"description\":\"номер - id используемой карты\"},\"cardAssociation\":{\"type\":\"string\",\"description\":\"Реестр карточных ассоциаций\",\"enum\":[\"VISA\",\"MC\",\"AE\"]},\"1stStepCardDetails\":{\"type\":\"object\",\"description\":\"детали для первого окна\",\"required\":[\"buttonText\"],\"properties\":{\"buttonText\":{\"type\":\"string\",\"description\":\"текст на кнопке перехода на 2е окно\"},\"rows\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"row\":{\"type\":\"string\",\"description\":\"id строки детализации текста\"},\"textLeft\":{\"type\":\"string\"},\"textRight\":{\"type\":\"string\"},\"textColour\":{\"type\":\"string\"}}}},\"\":{\"type\":\"string\"}}},\"2ndStepCardDetails\":{\"type\":\"object\",\"description\":\"детали для первого окна\",\"properties\":{\"cardDetailText\":{\"type\":\"string\",\"description\":\"текст для второго окна\"},\"cardDetailHeading\":{\"type\":\"string\",\"description\":\"текст - заговолог для второго окна\"},\"cardDetailButtons\":{\"type\":\"array\",\"description\":\"поле с деталями кнопок\",\"items\":{\"type\":\"object\",\"properties\":{\"ButtonText\":{\"type\":\"string\",\"description\":\"текст на кнопке\"},\"PosstiveFlag\":{\"type\":\"boolean\",\"description\":\"флаг определяющий если кнопка для позитивного ответа (\\\"true\\\" = positive)\"},\"buttonResponse\":{\"type\":\"string\",\"description\":\"код нажатой кнопки. передается в рамках отдельного POST запроса\"}}}}}}},\"required\":[\"activityId\",\"datetime\",\"trans_amt\",\"trans_details\",\"currency_id\",\"categoryVisibleName\",\"1stStepCardDetails\",\"2ndStepCardDetails\"],",
                        "examples": {
                            "application/json": {
                                "activities": [
                                    {
                                        "activityId": 5210930,
                                        "datetime": "26.02.2016 12:53:43",
                                        "trans_amt": 23600,
                                        "trans_details": "British Airways",
                                        "trans_type": "online",
                                        "currency_id": "RUR",
                                        "categoryVisibleName": "Travel",
                                        "usedCard": "8465",
                                        "cardAssociation": "VISA",
                                        "1stStepCardDetails": {
                                            "buttonText": "Take recommendation",
                                            "rows": [
                                                {
                                                    "row": "1",
                                                    "textLeft": "Higher goals",
                                                    "textRight": "+140 FF",
                                                    "textColour": "green"
                                                }
                                            ]
                                        },
                                        "2ndStepCardDetails": {
                                            "cardDetailText": "All insured travel risk and personal items theft coverage that would cost 7 EUR per day of your vacation",
                                            "cardDetailHeading": "Would take out a travel insurance provided by Aviva?",
                                            "cardDetailButtons": [
                                                {
                                                    "ButtonText": "No, thanks",
                                                    "possitiveFlag": false,
                                                    "buttonResponse": "leave"
                                                },
                                                {
                                                    "ButtonText": "Yes, please",
                                                    "possitiveFlag": true,
                                                    "buttonResponse": "take"
                                                }
                                            ]
                                        }
                                    },
                                    {
                                        "activityId": 5210940,
                                        "datetime": "01.03.2016 18:40:00",
                                        "trans_amt": 780,
                                        "trans_details": "Uber",
                                        "trans_type": "offline",
                                        "currency_id": "RUR",
                                        "categoryVisibleName": "`Travel",
                                        "usedCard": "0039",
                                        "cardAssociation": "VISA",
                                        "1stStepCardDetails": {
                                            "buttonText": "Provide Context"
                                        },
                                        "2ndStepCardDetails": {
                                            "cardDetailText": "",
                                            "cardDetailHeading": "Should we book this as your business travel expense you’d claim later?",
                                            "cardDetailButtons": [
                                                {
                                                    "ButtonText": "No, thanks",
                                                    "possitiveFlag": false,
                                                    "buttonResponse": "take"
                                                },
                                                {
                                                    "ButtonText": "Yes, please",
                                                    "possitiveFlag": true,
                                                    "buttonResponse": "take"
                                                }
                                            ]
                                        }
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        },
        "/ffPyramid": {
            "get": {
                "operationId": "GET_ffPyramid",
                "summary": "FF Pyramid stats",
                "description": "<p>Предоставляет статистику из FF пырамиды клиента, в категориях FFпырамиды.</p>\n<p>json объект <a href=\"/v1.0/models/ffpyramidcategory\" class=\"undefined\">ffPyramidCategory</a>   имеет следующие properties:</p>\n<PRE>\n<code class=language-json»>\n<span class=token punctuation»>{</span>\n<span class=\"token property\">\"VisibleName\"</span> <span class=\"token operator\">:</span> <span class=\"token string\">\"Higher Goals\"</span>\n<span class=\"token property\">\"Name\"</span> <span class=\"token operator\">:</span> <span class=\"token string\">\"#higherGoals\"</span>\n<span class=\"token property\">\"TotalSum\"</span> <span class=\"token operator\">:</span> <span class=\"token integer\">24580</span>\n<span class=\"token property\">\"Currency\"</span> <span class=\"token operator\">:</span> <span class=\"token string\">\"RUR\"</span>\n<span class=\"token property\">\"ffPoints\"</span> <span class=\"token operator\">:</span> <span class=\"token integer\">750</span>\n<span class=\"token property\">\"ffPointsRatio\"</span> <span class=\"token operator\">:</span> <span class=\"token integer\">\"21</span>\n<span class=\"token property\">\"primaryColor\"</span> <span class=\"token operator\">:</span> <span class=\"token string\">\"#419BF9\"</span>\n<span class=token punctuation»>}</span>\n</code>\n</pre>\n<br>",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "ffPyramidCategories": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "VisibleName": {
                                                "type": "string"
                                            },
                                            "Name": {
                                                "type": "string"
                                            },
                                            "TotalSum": {
                                                "type": "integer"
                                            },
                                            "Currency": {
                                                "type": "string"
                                            },
                                            "ffPoints": {
                                                "type": "integer"
                                            },
                                            "ffPointsRatio": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "examples": {
                            "application/json": {
                                "ffPyramidCategories": [
                                    {
                                        "VisibleName": "Higher Goals",
                                        "Name": "higherGoals",
                                        "TotalSum": 24580,
                                        "Currency": "RUR",
                                        "ffPoints": 750,
                                        "ffPointsRatio": 21
                                    },
                                    {
                                        "VisibleName": "Social Desires",
                                        "Name": "socialDesires",
                                        "TotalSum": 61840,
                                        "Currency": "RUR",
                                        "ffPoints": 380,
                                        "ffPointsRatio": 63
                                    },
                                    {
                                        "VisibleName": "Bare Necessities",
                                        "Name": "bareNecessities",
                                        "TotalSum": 30875,
                                        "Currency": "RUR",
                                        "ffPoints": 175,
                                        "ffPointsRatio": 27
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        },
        "/recommendations/{recommendationId}": {
            "parameters": [
                {
                    "name": "recommendationId",
                    "in": "path",
                    "required": true,
                    "type": "string"
                }
            ],
            "post": {
                "operationId": "POST_recommendations-recommendationId",
                "summary": "Save user action on Recommendation",
                "description": "<p><h4>Сохранение выбора  реакции пользователя на рекоммендацию</h4>\n<br>\nДанное API сохраняет результат действий пользователя с Рекоммендацией - выбор одного из двух вариантов ответа.</p>\n<br>\n<br>\n<p>В вызове передается ИД рекоммендации (recommendationId) и содержание атрибута <code>buttonResponse </code> кнопки, которая была нажата.\n<br>\n<br>\n<code>buttonResponse </code> содержится в объекте Recommendation, предедыдущего  вызова (<code><a href=\"/v1.0/models/recommnedation\" class=\"undefined\">Recommnedation</a></code> для получения деталей рекоммендаций.</p>\n",
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "buttonResponse": {
                                    "type": "string"
                                }
                            },
                            "example": {
                                "buttonResponse": "take"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/Transactions/{category}": {
            "parameters": [
                {
                    "name": "category",
                    "in": "path",
                    "description": "Название категроии. reference на 'category.name'",
                    "required": true,
                    "type": "string",
                    "default": "groceries"
                }
            ],
            "get": {
                "operationId": "GET_Transactions-category",
                "summary": "Transactions in Category",
                "description": "<p>Возвращает список трансакций в данной категории, за определенный период.</p>\n<p>ID категории для которой требуется получить данные, передается в URL как параметр, и берется из property <code> ffCategory.Name </code> объекта <code> <a href=\"/v1.0/models/ffcategory\" class=\"undefined\">ffCategory</a> </code>.</p>\n<p>Период, для которого требуются трансакции, передвется как  &quot;query string&quot; <code>period</code>.</p>\n",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "period",
                        "in": "query",
                        "description": "Период, за который предоставляется статистика",
                        "required": false,
                        "type": "string",
                        "default": "month",
                        "enum": [
                            "day",
                            "week",
                            "2weeks",
                            "month",
                            "all"
                        ]
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": "{\"type\":\"object\",\"properties\":{\"transactions\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"ffcategory\":{\"type\":\"string\"},\"TRANS_DATE\":{\"type\":\"string\"},\"TRANS_DETAILS\":{\"type\":\"string\"},\"TRANS_AMT\":{\"type\":\"string\"},\"TRANS_COUNTRY\":{\"type\":\"string\"},\"CURRENCY_ID\":{\"type\":\"string\",\"description\":\"3х значный ISO код валюты трансакции\"}},",
                        "examples": {
                            "application/json": {
                                "transactions": [
                                    {
                                        "TRANS_DATE": "26.02.2016 12:53:43",
                                        "TRANS_DETAILS": "KAFE LIGA PAP",
                                        "TRANS_AMT": "1360,00000",
                                        "TRANS_COUNTRY": "RUSSIA",
                                        "CURRENCY_ID": "RUR"
                                    },
                                    {
                                        "TRANS_DATE": "29.02.2016 14:53:53",
                                        "TRANS_DETAILS": "TEREMOK CHISTIY PRUDY",
                                        "TRANS_AMT": "317,00000",
                                        "TRANS_COUNTRY": "RUSSIA",
                                        "CURRENCY_ID": "RUR"
                                    },
                                    {
                                        "TRANS_DATE": "01.03.2016 14:55:23",
                                        "TRANS_DETAILS": "OZIN CATERING",
                                        "TRANS_AMT": "345,00000",
                                        "TRANS_COUNTRY": "RUSSIA",
                                        "CURRENCY_ID": "RUR"
                                    },
                                    {
                                        "TRANS_DATE": "02.03.2016 16:44:42",
                                        "TRANS_DETAILS": "BENVENUTO",
                                        "TRANS_AMT": "2830,00000",
                                        "TRANS_COUNTRY": "RUSSIA",
                                        "CURRENCY_ID": "RUR"
                                    },
                                    {
                                        "TRANS_DATE": "03.03.2016 15:00:38",
                                        "TRANS_DETAILS": "OZIN CATERING",
                                        "TRANS_AMT": "215,00000",
                                        "TRANS_COUNTRY": "RUSSIA",
                                        "CURRENCY_ID": "RUR"
                                    },
                                    {
                                        "TRANS_DATE": "03.03.2016 15:01:06",
                                        "TRANS_DETAILS": "OZIN CATERING",
                                        "TRANS_AMT": "120,00000",
                                        "TRANS_COUNTRY": "RUSSIA",
                                        "CURRENCY_ID": "RUR"
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "activity": {
            "title": "Activity",
            "type": "object",
            "properties": {
                "activityId": {
                    "type": "integer",
                    "description": "уникальный идентификатор активности в системе"
                },
                "datetime": {
                    "type": "string",
                    "description": "время и дата трансакции в UTC формате"
                },
                "trans_amt": {
                    "type": "number",
                    "description": "сума трансакции"
                },
                "trans_details": {
                    "type": "string",
                    "description": "Название места - merchant"
                },
                "trans_type": {
                    "type": "string",
                    "description": "Тип трансакции - online/offline. "
                },
                "currency_id": {
                    "type": "string",
                    "description": "3х значный ISO код валюты"
                },
                "categoryVisibleName": {
                    "type": "string",
                    "description": "название FF категории трансакции"
                },
                "usedCard": {
                    "type": "string",
                    "description": "номер - id используемой карты"
                },
                "cardAssociation": {
                    "$ref": "#/definitions/used-card-enumeration"
                },
                "1stStepCardDetails": {
                    "type": "object",
                    "description": "детали для первого окна",
                    "required": [
                        "buttonText"
                    ],
                    "properties": {
                        "buttonText": {
                            "type": "string",
                            "description": "текст на кнопке перехода на 2е окно"
                        },
                        "rows": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "row": {
                                        "type": "string",
                                        "description": "id строки детализации текста"
                                    },
                                    "textLeft": {
                                        "type": "string"
                                    },
                                    "textRight": {
                                        "type": "string"
                                    },
                                    "textColour": {
                                        "type": "string"
                                    }
                                }
                            }
                        },
                        "": {
                            "type": "string"
                        }
                    }
                },
                "2ndStepCardDetails": {
                    "type": "object",
                    "description": "детали для первого окна",
                    "properties": {
                        "cardDetailText": {
                            "type": "string",
                            "description": "текст для второго окна"
                        },
                        "cardDetailHeading": {
                            "type": "string",
                            "description": "текст - заговолог для второго окна"
                        },
                        "cardDetailButtons": {
                            "type": "array",
                            "description": "поле с деталями кнопок",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "ButtonText": {
                                        "type": "string",
                                        "description": "текст на кнопке"
                                    },
                                    "PosstiveFlag": {
                                        "type": "boolean",
                                        "description": "флаг определяющий если кнопка для позитивного ответа (\"true\" = positive)"
                                    },
                                    "buttonResponse": {
                                        "type": "string",
                                        "description": "код нажатой кнопки. передается в рамках отдельного POST запроса"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "required": [
                "activityId",
                "datetime",
                "trans_amt",
                "trans_details",
                "currency_id",
                "categoryVisibleName",
                "1stStepCardDetails",
                "2ndStepCardDetails"
            ],
            "example": {
                "activityId": 5210930,
                "datetime": "26.02.2016 12:53:43",
                "trans_amt": 23600,
                "trans_details": "British Airways",
                "trans_type": "online",
                "currency_id": "RUR",
                "categoryVisibleName": "Travel",
                "usedCard": "8465",
                "cardAssociation": "VISA",
                "1stStepCardDetails": {
                    "buttonText": "Take recommendation",
                    "rows": [
                        {
                            "row": "1",
                            "textLeft": "Higher goals",
                            "textRight": "+140 FF",
                            "textColour": "green"
                        }
                    ]
                },
                "2ndStepCardDetails": {
                    "cardDetailText": "All insured travel risk and personal items theft coverage that would cost 7 EUR per day of your vacation",
                    "cardDetailHeading": "Would take out a travel insurance provided by Aviva?",
                    "cardDetailButtons": [
                        {
                            "ButtonText": "No, thanks",
                            "possitiveFlag": false,
                            "buttonResponse": "leave"
                        },
                        {
                            "ButtonText": "Yes, please",
                            "possitiveFlag": true,
                            "buttonResponse": "take"
                        }
                    ]
                }
            }
        },
        "category": {
            "title": "Category",
            "type": "object",
            "properties": {
                "ffCategoryVisibleName": {
                    "type": "string"
                },
                "ffCategory": {
                    "type": "string"
                },
                "Operations": {
                    "type": "integer"
                },
                "TotalSum": {
                    "type": "integer"
                },
                "Currency": {
                    "type": "string",
                    "description": "3х значный ISO код валюты"
                },
                "ffPoints": {
                    "type": "integer"
                }
            },
            "example": {
                "ffCategoryVisibleName": "Total for 30 days",
                "ffCategory": "total",
                "Operations": 148,
                "TotalSum": 71602,
                "Currency": "RUR",
                "ffPoints": 1785
            }
        },
        "clientid": {
            "title": "clientID",
            "type": "object",
            "properties": {
                "clientID": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 99999999
                }
            },
            "required": [
                "clientID"
            ],
            "example": {
                "clientID": 12
            }
        },
        "pyramidcategory": {
            "title": "PyramidCategory",
            "type": "object",
            "properties": {
                "pyramidCategoryVisibleName": {
                    "type": "string"
                },
                "pyramidCategory": {
                    "type": "string"
                },
                "TotalSum": {
                    "type": "integer"
                },
                "Currency": {
                    "type": "string",
                    "description": "3х значный ISO код валюты трансакции"
                },
                "ffPoints": {
                    "type": "integer"
                }
            },
            "example": {
                "pyramidCategoryVisibleName": "Higher Goals",
                "pyramidCategory": "higherGoals",
                "TotalSum": 24580,
                "Currency": "RUR",
                "ffPoints": 750
            }
        },
        "recommendation": {
            "title": "Recommendation",
            "type": "object",
            "properties": {
                "recommendationId": {
                    "type": "integer"
                },
                "recommendationStatus": {
                    "type": "string",
                    "description": "статус рекоммендации.",
                    "enum": [
                        "new",
                        "active",
                        "filled",
                        "expired"
                    ]
                },
                "recommendationType": {
                    "type": "string",
                    "description": "тип рекомендации.  Испроьзуется для текста шапки карточки с рекомендацие"
                },
                "recommendationCategory": {
                    "type": "string",
                    "description": "тип рекомендации.  Испроьзуется для текста шапки карточки с рекомендацие"
                },
                "occurence": {
                    "type": "string",
                    "description": "Время следующего появления рекомендаций. возможные вараианты: \"next Monday\"; \"next Week\"; \"next Month\""
                },
                "recommendationAmount": {
                    "type": "number",
                    "description": "сума на которую расчитывает реукомендация"
                },
                "currency_id": {
                    "type": "string",
                    "description": "3х значный ISO код валюты"
                },
                "usedCard": {
                    "type": "string",
                    "description": "номер - id используемой карты"
                },
                "cardAssociation": {
                    "$ref": "#/definitions/used-card-enumeration"
                },
                "1stStepCardDetails": {
                    "type": "object",
                    "description": "детали для первого окна",
                    "required": [
                        "buttonText"
                    ],
                    "properties": {
                        "buttonText": {
                            "type": "string",
                            "description": "текст на кнопке перехода на 2е окно"
                        },
                        "rows": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "row": {
                                        "type": "string",
                                        "description": "id строки детализации текста"
                                    },
                                    "textLeft": {
                                        "type": "string"
                                    },
                                    "textRight": {
                                        "type": "string"
                                    },
                                    "textColour": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "2ndStepCardDetails": {
                    "type": "object",
                    "description": "детали для первого окна",
                    "required": [
                        "cardDetailText",
                        "cardDetailHeading",
                        "cardDetailButtons"
                    ],
                    "properties": {
                        "cardDetailText": {
                            "type": "string",
                            "description": "текст для второго окна"
                        },
                        "cardDetailHeading": {
                            "type": "string",
                            "description": "текст - заговолог для второго окна"
                        },
                        "cardDetailButtons": {
                            "type": "array",
                            "description": "поле с деталями кнопок",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "ButtonText": {
                                        "type": "string",
                                        "description": "текст на кнопке"
                                    },
                                    "possitiveFlag": {
                                        "type": "boolean",
                                        "description": "флаг определяющий если кнопка для позитивного ответа (\"1\" = positive)"
                                    },
                                    "buttonResponse": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "ButtonText",
                                    "possitiveFlag",
                                    "buttonResponse"
                                ]
                            }
                        }
                    }
                }
            },
            "required": [
                "recommendationId",
                "recommendationStatus",
                "recommendationType",
                "recommendationCategory",
                "occurence",
                "recommendationAmount",
                "currency_id",
                "usedCard",
                "cardAssociation",
                "1stStepCardDetails",
                "2ndStepCardDetails"
            ],
            "example": {
                "recommendationId": 16983,
                "recommendationStatus": "new",
                "recommendationType": "Auchan",
                "recommendationCategory": "Groceries",
                "occurence": "every Tuesday",
                "recommendationAmount": 260,
                "currency_id": "EUR",
                "usedCard": "0039",
                "cardAssociation": "MC",
                "1stStepCardDetails": {
                    "buttonText": "Take recommendation",
                    "rows": [
                        {
                            "row": "",
                            "textLeft": "",
                            "textRight": "",
                            "textColour": ""
                        }
                    ]
                },
                "2ndStepCardDetails": {
                    "cardDetailText": "This recomendation is based on most of your Groceries shopping done around Tuesday every other week. \n Milk \n Yogurt \n Grapefruit \n Banana",
                    "cardDetailHeading": "We have calculated your typical shopping list and have thrown in a special from our partner, Auchan",
                    "cardDetailButtons": [
                        {
                            "ButtonText": "Leave it",
                            "possitiveFlag": false,
                            "buttonResponse": "leave"
                        },
                        {
                            "ButtonText": "Take it",
                            "possitiveFlag": true,
                            "buttonResponse": "take"
                        }
                    ]
                }
            }
        },
        "transaction": {
            "title": "Transaction",
            "type": "object",
            "properties": {
                "ffcategory": {
                    "type": "string"
                },
                "TRANS_DATE": {
                    "type": "string"
                },
                "TRANS_DETAILS": {
                    "type": "string"
                },
                "TRANS_AMT": {
                    "type": "string"
                },
                "TRANS_COUNTRY": {
                    "type": "string"
                },
                "CURRENCY_ID": {
                    "type": "string",
                    "description": "3х значный ISO код валюты трансакции"
                }
            },
            "example": {
                "ffcategory": "fastfood",
                "TRANS_DATE": "26.02.2016 12:53:43",
                "TRANS_DETAILS": "KAFE LIGA PAP",
                "TRANS_AMT": "1360,00000",
                "TRANS_COUNTRY": "RUSSIA",
                "CURRENCY_ID": "RUR"
            }
        },
        "used-card-enumeration": {
            "title": "used card enumeration",
            "type": "string",
            "description": "Реестр карточных ассоциаций",
            "enum": [
                "VISA",
                "MC",
                "AE"
            ]
        }
    }
}